sudo: false
cache: false
language: node_js
node_js:
  - '8'
  - '10'
before_install:
  - npm install -g npminstall
install:
  - npminstall
  - npminstall codecov
script:
  - npm run ci
after_script:
  - codecov
